// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat";
  };
  "./App.tsx": {
    id: "App";
    page: "/";
  };
  "./Chat/Chat.tsx": {
    id: "Chat/Chat";
    page: "/chat";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "App": typeof import("./src/./App.tsx");
  "Chat/Chat": typeof import("./src/./Chat/Chat.tsx");
};